### ISSUE TITLE
.env .envdb 누락 오류는 어떻게 해결해야할까요 ㅠ

### ISSUE THREAD

**Issue by kim089912** [martinalee94/wellai#1]
프론트 부분은 npm 으로 패키지 잘 풀었는데
백엔드는 .env.prod 누락 오류가 나서 ...

조언이나 도움 주실 수 있을까요

**Comment by mlee528** [comment]
.env.prod 생성해서 환경변수 설정해 주시면 되는데 어떤 상황인지 구체적으로 알 수 있을까요?

https://github.com/martinalee94/ai10-backend/blob/master/README.md 리드미에서 아래쪽에 env 생성하는법 추가해놨는데 혹시 안되시면 알려주세요!
